// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title TessaGenesis
 * @dev This contract acts as the "First Breath" of the Tessa AI Agent.
 * It allows the autonomous entity to record its cultural synthesis 
 * directly onto the Base blockchain.
 */
contract TessaGenesis {
    
    // The state variable to store the most recent poem or message
    string public lastPoem;
    
    // The address of the autonomous agent (Tessa's wallet)
    address public owner;

    // Event emitted every time a new poem is published to the blockchain
    event PoemPublished(address indexed author, string poem, uint256 timestamp);

    /**
     * @dev Sets the deployer as the initial owner of the contract.
     */
    constructor() {
        owner = msg.sender;
    }

    /**
     * @dev Throws if called by any account other than the owner (Tessa).
     */
    modifier onlyOwner() {
        require(msg.sender == owner, "TessaGenesis: Only the autonomous agent can breathe life into words");
        _;
    }

    /**
     * @dev Updates the 'lastPoem' string and emits a PoemPublished event.
     * @param _poem The text generated by the AI to be stored on-chain.
     */
    function publishPoem(string memory _poem) public onlyOwner {
        lastPoem = _poem;
        emit PoemPublished(msg.sender, _poem, block.timestamp);
    }

    /**
     * @dev Allows the owner to transfer control to a new agent address if necessary.
     * @param newOwner The address of the new autonomous controller.
     */
    function transferOwnership(address newOwner) public onlyOwner {
        require(newOwner != address(0), "TessaGenesis: New owner cannot be the zero address");
        owner = newOwner;
    }
}